name: Sync Docs → Vertex AI

on:
  workflow_dispatch:      # 手動トリガー
  push:                   # /docs/*.md を push したとき
    paths:
      - 'docs/**.md'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリ取得
      - uses: actions/checkout@v4

      # 2) gcloud CLI をセットアップ
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 3) Markdown を GCS バケットへコピー
      - name: Copy docs to GCS
        run: |
          gsutil -m rsync -r docs gs://$GCS_BUCKET/docs

      # 4) Vertex AI Search に取り込み
      - name: Import into Vertex AI Search
        run: |
          gcloud discoveryengine data-stores import documents \
            --project=$GCP_PROJECT_ID \
            --location=global \
            --data-store=$DATASTORE_ID \
            --gcs-source=gs://$GCS_BUCKET/docs/*.md \
            --auto-generate-ids
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          DATASTORE_ID: ${{ secrets.DATASTORE_ID }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
