name: Sync Docs → Vertex AI

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**.md'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v4

      # 2) 認証
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3) gcloud CLI （gsutil 用）
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 4) Markdown → GCS バケット
      - name: Copy docs to GCS
        run: |
          gsutil -m rsync -r docs gs://${{ secrets.GCS_BUCKET }}/docs
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

      # 5) REST API で Vertex AI Search に取り込み
      - name: Import documents via REST API
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          curl -X POST \
            -H "Authorization: Bearer ${ACCESS_TOKEN}" \
            -H "Content-Type: application/json" \
            "https://discoveryengine.googleapis.com/v1/projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/dataStores/${{ secrets.DATASTORE_ID }}/branches/default_branch:importDocuments" \
            -d '{
                  "gcsSource": {
                    "inputUris": ["gs://${{ secrets.GCS_BUCKET }}/docs/*.md"]
                  },
                  "autoGenerateIds": true
               }'
