name: Sync Docs → Vertex AI

on:
  workflow_dispatch:
  push:
    paths:
      - "**.md"            # ルート直下の .md でもトリガー

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    # 1) リポジトリ取得
    - uses: actions/checkout@v4

    # 2) GCP 認証
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 3) gcloud / gsutil セットアップ
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # 4) docs/ フォルダを必ず作成し、.md を移動
    - name: Ensure docs/ exists
      run: |
        mkdir -p docs
        # ルート直下 *.md を docs/ に集約（既にあるものは上書きしない）
        for f in *.md; do
          [ -e "$f" ] && mv -f "$f" docs/ || true
        done
        echo "=== files in docs/ ==="
        ls -1 docs

    # 5) GCS に同期
    - name: Upload to GCS
      run: |
        gsutil -m rsync -r docs gs://${{ secrets.GCS_BUCKET }}/docs

    # 6) Vertex AI Search へ取り込み（REST API）
    - name: Import into Vertex AI Search
      run: |
        ACCESS_TOKEN=$(gcloud auth print-access-token)
        curl -sSf -X POST \
          -H "Authorization: Bearer ${ACCESS_TOKEN}" \
          -H "Content-Type: application/json" \
          "https://discoveryengine.googleapis.com/v1/projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/collections/default_collection/dataStores/${{ secrets.DATASTORE_ID }}/branches/default_branch:importDocuments" \
          -d '{
                "gcsSource": {
                  "inputUris": ["gs://${{ secrets.GCS_BUCKET }}/docs/*.md"]
                },
                "autoGenerateIds": true
              }'
