name: Sync Docs → Vertex AI (safe)

on:
  workflow_dispatch:
  push:
    paths:
      - '**.md'          # ルートの md でも起動

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # === 認証 & gcloud ===
      - uses: google-github-actions/auth@v2
        with: {credentials_json: ${{ secrets.GCP_SA_KEY }}}

      - uses: google-github-actions/setup-gcloud@v2
        with: {project_id: ${{ secrets.GCP_PROJECT_ID }}}

      # === 必ず docs/ に MD が存在するよう保証 ===
      - name: Prepare docs directory
        run: |
          mkdir -p docs
          find . -maxdepth 1 -name '*.md' -exec mv -t docs {} +
          echo "Local docs now:" && ls -l docs

      # === GCS に同期 ===
      - name: Upload to GCS
        run: |
          gsutil -m rsync -r docs gs://${{ secrets.GCS_BUCKET }}/docs

      # === REST API で取り込み ===
      - name: Import to Vertex AI Search
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          curl -s -X POST \
            -H "Authorization: Bearer ${ACCESS_TOKEN}" \
            -H "Content-Type: application/json" \
            "https://discoveryengine.googleapis.com/v1/projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/dataStores/${{ secrets.DATASTORE_ID }}/branches/default_branch:importDocuments" \
            -d '{
                  "gcsSource": {
                    "inputUris": ["gs://${{ secrets.GCS_BUCKET }}/docs/*.md"]
                  },
                  "autoGenerateIds": true
                }' \
            | jq .
