- name: Import to Vertex AI Search
  run: |
    ACCESS_TOKEN=$(gcloud auth print-access-token)
    curl -s -f -X POST \
      -H "Authorization: Bearer ${ACCESS_TOKEN}" \
      -H "Content-Type: application/json" \
      "https://discoveryengine.googleapis.com/v1/projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/collections/default_collection/dataStores/${{ secrets.DATASTORE_ID }}/branches/default_branch:importDocuments" \
      -d '{
            "gcsSource": {
              "inputUris": [ "gs://${{ secrets.GCS_BUCKET }}/docs/*.md" ]
            },
            "autoGenerateIds": true
          }'
